### ISSUE TITLE
How to insert a dart object to javascript code and access packages inside js?

### ISSUE THREAD

**Issue by nabeghe** [anuragvohraec/jsengine#1]
I need to inject created objects in dart to js code or import packages from js. how can I do that?

**Comment by anuragvohraec** [comment]
You can't pass the Dart object directly, you need to convert them to String, wrap your JS code around that string and get it executed. 

For example:

```
JSEngine jsEngine = JSEngine(pathToLibSoFile: "jerryscriptwrapper/build/libjerryscriptwrapper.so");
int a= 5;
unt b= 3;
String jscode = ''' function sum(a,b){
return a+b;
}
sum($a, $b); //a and b are passed from dart using Strings
''';
String result = jsEngine.runJSCode(jscode);
print(result); //will print 8
```

If you wanted to pass complex object, convert them to JSON String then pass it inside the code.
Inside the jscode you can use JSON.parse to convert it into Javascript objects, and once your processing is done, you can return it back as JSON.stringify .
And in Dart youc an convert back that string returned to Dart object.
dart:convert lib has jsonEncode and jsonDecode function to do juts what I am saying.

**Comment by anuragvohraec** [comment]
Will be closing this issue, as no more action required.
My last answer responds to original question asked in this issue.
